# Site settings
title: SilentLines
email: silentlines.co.uk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Music, poetry and other creative endeavours by Cara Thompson and friends. 
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
# url: "http://silentlines.co.uk" # the base hostname & protocol for your site
twitter_username: crthompson
github_username:  crthompson

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"